local HELPS = {
	"The Developer is Supreme", "Life is Hell", "The Developer is Supreme",
	"Jump before you leap",
}

function init(self)
	if #HELPS > 0 then
		local random = math.random(1, #HELPS)
		gui.set_text(gui.get_node("help"), HELPS[random])
	end

	local node = gui.get_node("loader")
	gui.set_position(node, vmath.vector3(480, -100, 0))
	gui.animate(node, "position.y", 100, gui.EASING_OUTBOUNCE, 2)
end