local M = 
{
	{
		name = "Pistol",
		Description = "A traditional small pistol to calm your mind.",
		type = hash("bullet-6");
		speed = 300,
		bullets_per_second = 2,
		bullet_per_shot = 1,	--more than 1 for shotguns
		damage = 1,
		magazine_size = 10,
		reload_time = 1.5, 
		move_and_fire = true,
		distance = 300,
		laser_sight = false,
	},
	{
		name = "Throwing Knives",
		Description = "Rusty throwing knives that someone picked up from trash.",
		speed = 100,
		type = hash("bullet-16"),
		bullets_per_second = 2,
		bullet_per_shot = 1,	--more than 1 for shotguns
		damage = 3,
		magazine_size = 5,
		reload_time = 1.5, 
		move_and_fire = true,
		distance = 200,
		laser_sight = false,
	},
	{
		name = "SMG",
		Description = "The younger brother of a minigun. Rapid fire rate with medium damage.",
		speed = 200,
		type = hash("bullet-10"),
		bullets_per_second = 10,
		bullet_per_shot = 1,	--more than 1 for shotguns
		damage = 1.5,
		magazine_size = 25,
		reload_time = 1.5, 
		move_and_fire = true,
		distance = 400,
		laser_sight = false,
	},
	{
		name = "Magical Staff",
		Description = "Tool of a necromancer. Wield it with great responsibility.",
		type = hash("bullet-12"),
		speed = 250,
		bullets_per_second = 5,
		bullet_per_shot = 3,	--more than 1 for shotguns
		damage = 3,
		magazine_size = 25,
		reload_time = 1.5, 
		move_and_fire = true,
		distance = 300,
		laser_sight = false,
	},
	{
		name = "Laser Beam",
		Description = "Let there be lasers",
		speed = 300,
		type = hash("bullet-15"),
		bullets_per_second = 1,
		bullet_per_shot = 1,	--more than 1 for shotguns
		damage = 3,
		magazine_size = 50,
		reload_time = 1.5, 
		move_and_fire = true,
		distance = 500,
		laser_sight = false,
	},
	{
		name = "Assault Rifle",
		Description = "Slightly less active than a minigun but with more heat.",
		speed = 350,
		type = hash("bullet-13"),
		bullets_per_second = 15,
		bullet_per_shot = 1,	--more than 1 for shotguns
		damage = 3,
		magazine_size = 30,
		reload_time = 1.5, 
		move_and_fire = true,
		distance = 500,
		laser_sight = true,
	},
	{
		name = "Shotgun",
		Description = "Multishot, Heat Packed firing.",
		type = hash("bullet-6"),
		speed = 250,
		bullets_per_second = 1,
		bullet_per_shot = 5,	--more than 1 for shotguns
		damage = 3,
		magazine_size = 25,
		reload_time = 3, 
		move_and_fire = true,
		distance = 300,
		laser_sight = false,
	},
	{
		name = "Revolver",
		Description = "The power of a bull X 6.",
		type = hash("bullet-8"),
		speed = 200,
		bullets_per_second = 3,
		bullet_per_shot = 1,	--more than 1 for shotguns
		damage = 3,
		magazine_size = 6,
		reload_time = 1.5, 
		move_and_fire = true,
		distance = 500,
		laser_sight = false,
	},
	{
		name = "Sniper",
		Description = "Single Shot Kill.",
		type = hash("bullet-14"),
		speed = 350,
		bullets_per_second = 1,
		bullet_per_shot = 1,	--more than 1 for shotguns
		damage = 6,
		magazine_size = 5,
		reload_time = 1.5, 
		move_and_fire = true,
		distance = 500,
		laser_sight = true,
	},
	{
		name = "Combat Shotgun",
		Description = "Short Range InstaKill.",
		type = hash("bullet-15"),
		speed = 200,
		bullets_per_second = 2,
		bullet_per_shot = 5,	--more than 1 for shotguns
		damage = 4,
		magazine_size = 10,
		reload_time = 2, 
		move_and_fire = true,
		distance = 500,
		laser_sight = true,
	},
}

return M